spring.application.name=SkillCore
spring.datasource.url=jdbc:mysql://localhost:3306/skillcore
spring.datasource.username=root
spring.datasource.password=Bhulgaya@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true
file.upload-dir=uploads
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mdhuraibrasool@gmail.com
spring.mail.password=xgilfbuqbdzolrog
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.starttls.required=true
jwt.secret=T9tJ4RkKpFpJtZ3hT9e4fSd3yD2A0sJ+RplDkmtx7g3lsKzLgFh1ZP6STXc0bK8R8uFSW1Vdn2rZPzKpsHUxJA==
jwt.expirationMs=86400000

# allow larger uploads
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


logging.level.org.springframework.security=DEBUG




